# Generated by Django 3.0.2 on 2020-01-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerphotos',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner_photos', to='pages.Banner'),
        ),
    ]
