# Generated by Django 3.0.2 on 2020-01-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_socialmedialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialinks',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialmedia_links', to='pages.Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='pradeep@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(default='kapan', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='9843694018'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='icon',
            field=models.ImageField(default='', upload_to='social_medias/'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='link',
            field=models.URLField(default='www.google.com', max_length=255),
        ),
    ]
