# Generated by Django 3.0.2 on 2020-01-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200107_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialmedia_links', to='pages.Contact'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='icon',
            field=models.ImageField(upload_to='social_medias/'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
