# Generated by Django 3.0.2 on 2020-01-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_contact_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.CharField(max_length=3),
        ),
    ]
