# Generated by Django 3.0.2 on 2020-01-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200107_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
