# Generated by Django 3.0.2 on 2020-01-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_newsletter_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
