# Generated by Django 3.0.2 on 2020-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200113_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
