# Generated by Django 3.0.2 on 2020-01-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200107_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
