# Generated by Django 3.0.2 on 2020-01-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200108_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
