# Generated by Django 3.0.2 on 2020-01-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200114_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fav',
            field=models.IntegerField(default=0),
        ),
    ]
