# Generated by Django 3.0.2 on 2020-01-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200130_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notific',
        ),
    ]
