# Generated by Django 3.0.2 on 2020-01-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200109_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(default='White', max_length=150),
        ),
    ]
