# Generated by Django 3.0.2 on 2020-01-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200109_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='color',
            field=models.TextField(default='White'),
        ),
    ]
