# Generated by Django 3.0.2 on 2020-01-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200109_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(default='White', max_length=150),
        ),
    ]
