# Generated by Django 3.0.2 on 2020-01-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200106_1218'),
        ('accounts', '0024_auto_20200109_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartproduct', to='products.Product'),
        ),
    ]
