# Generated by Django 3.0.2 on 2020-01-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200109_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitList',
        ),
    ]
