# Generated by Django 3.0.2 on 2020-01-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='color',
            field=models.CharField(default='White', max_length=150),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(max_length=150),
        ),
    ]
