# Generated by Django 3.0.2 on 2020-01-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200110_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='color',
            field=models.CharField(max_length=150),
        ),
    ]
