# Generated by Django 3.0.2 on 2020-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200110_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='media/default_user.png', null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
