# Generated by Django 3.0.2 on 2020-01-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200110_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
