# Generated by Django 3.0.2 on 2020-01-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200110_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='color',
        ),
    ]
