# Generated by Django 3.0.2 on 2020-01-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200105_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='type',
            name='slug',
        ),
    ]
