# Generated by Django 3.0.2 on 2020-01-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200105_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availabe',
            field=models.BooleanField(default=True),
        ),
    ]
