# Generated by Django 3.0.2 on 2020-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200105_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availabe',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
