# Generated by Django 3.0.2 on 2020-01-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200106_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availabe',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
